title: Emily Wilson

description:
description2: I'm a computer science student at Georgia Tech, specializing in Media and Intelligence. I intend to go into software engineering, specifically mobile development.

show_downloads: false

google_analytics:

theme: jekyll-theme-cayman

url: "http://emilywilson1.github.io"

githubusername: emilywilson1
githuburl: http://github.com/emilywilson1
linkedinusername: emilywilson62

encoding: utf-8
